name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Instalar browsers
        run: npx playwright install --with-deps

      - name: Rodar Testes
        run: npx playwright test --reporter=html

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Gera relatório Allure
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report